development:
  adapter: postgresql
  database: themeritshop_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: themeritshop_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: themeritshop_production
  pool: 5
  timeout: 5000
